function out = pinet_paper_reference_demo(varargin)
%PINET_PAPER_REFERENCE_DEMO Recreate the final PINET figure set.

rootDir = fileparts(mfilename('fullpath'));

p = inputParser;
addParameter(p, 'SavePath', fullfile(rootDir, 'results_paper_reference_demo'), @(x) ischar(x) || isstring(x));
addParameter(p, 'DataPath', fullfile(rootDir, 'data_paper_reference_demo'), @(x) ischar(x) || isstring(x));
addParameter(p, 'RealVectorSpacingBase', 350, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'ReconstructionVectors', true, @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

if ~exist(opts.SavePath, 'dir')
    mkdir(opts.SavePath);
end
if ~exist(opts.DataPath, 'dir')
    mkdir(opts.DataPath);
end

simulatedReal = {
    'Scattered electric field of an illuminated wire 1000'
};

fieldAndFourier = {
    'Fourier picture of scattered field'
    'Fourier picture of the scattered field after HPF of w over c'
    'Fourier picture of the scattered field after HPF of w over v'
    'Scattered electric field after HPF of w over c'
    'Scattered electric field after HPF of w over v'
};

reconstructionSet = {
    'Blurred reconstructed E with grid size of 30'
    'Median filtered reconstructed E with grid size of 200'
    'Perona-Malik diffused reconstructed E with grid size of 80'
    'Perona-Malik diffused reconstructed E with grid size of 110'
    'Perona-Malik diffused reconstructed E with grid size of 200'
    'Perona-Malik diffused reconstructed E with grid size of 500'
};

% Figure 1-style branch: static scattered field with zoomed real-space panel.
pinet_recreate_reference_set( ...
    'ReferencePath', fullfile(rootDir, 'approved_results_paper_reference_demo'), ...
    'SavePath', opts.SavePath, ...
    'DataPath', fullfile(opts.DataPath, 'simulated_real_static'), ...
    'UseVectorFields', true, ...
    'FigureFieldVariant', 'static', ...
    'FigureWindowFactor', 5, ...
    'FigureGridStyle', 'legacy', ...
    'RealSpaceZoomFactor', 25, ...
    'RealVectorSpacingBase', opts.RealVectorSpacingBase, ...
    'FigureNames', simulatedReal);

% Fourier and HPF branch: phase-bearing field family with the CLEO-style
% Fourier zoom and vector overlays.
pinet_recreate_reference_set( ...
    'ReferencePath', fullfile(rootDir, 'approved_results_paper_reference_demo'), ...
    'SavePath', opts.SavePath, ...
    'DataPath', fullfile(opts.DataPath, 'field_fourier_phase'), ...
    'UseVectorFields', true, ...
    'FigureFieldVariant', 'phase', ...
    'FigureWindowFactor', 5, ...
    'FigureGridStyle', 'legacy', ...
    'RealSpaceZoomFactor', 25, ...
    'RealVectorSpacingBase', opts.RealVectorSpacingBase, ...
    'FourierZoomFactor', 9, ...
    'FourierUseLog', false, ...
    'FourierVectors', true, ...
    'FourierVectorSpacingBase', 18, ...
    'FigureNames', fieldAndFourier);

% Reconstruction branch: keep the validated modular reconstruction path and
% export the reference reconstruction figures without vector overlays.
pinet_recreate_reference_set( ...
    'ReferencePath', fullfile(rootDir, 'approved_results_paper_reference_demo'), ...
    'SavePath', opts.SavePath, ...
    'DataPath', fullfile(opts.DataPath, 'reconstruction_clean'), ...
    'UseVectorFields', opts.ReconstructionVectors, ...
    'RealVectorSpacingBase', opts.RealVectorSpacingBase, ...
    'FigureNames', reconstructionSet);

out = struct();
out.savePath = string(opts.SavePath);
out.dataPath = string(opts.DataPath);
out.figureCount = numel([simulatedReal; fieldAndFourier; reconstructionSet]);
disp(out.savePath);
end
