function out = pinet_render_outputs(varargin)
%PINET_RENDER_OUTPUTS Generate the configured PINET outputs.

%% Load the figure plan
rootDir = fileparts(mfilename('fullpath'));
cfg = pinet_config(rootDir);

%% Parse runtime options
p = inputParser;
addParameter(p, 'SavePath', fullfile(rootDir, 'results_pinet_render'), @(x) ischar(x) || isstring(x));
addParameter(p, 'DataPath', fullfile(rootDir, 'data_pinet_render'), @(x) ischar(x) || isstring(x));
addParameter(p, 'RealVectorSpacingBase', cfg.defaults.RealVectorSpacingBase, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'ReconstructionVectors', cfg.defaults.ReconstructionVectors, @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

%% Prepare output folders
ensureDir(opts.SavePath);
ensureDir(opts.DataPath);

%% Render the simulated real-space figures
runConfiguredBranch(cfg, opts, ...
    'DataPath', fullfile(opts.DataPath, cfg.branch.simulatedReal.DataSubdir), ...
    'UseVectorFields', cfg.branch.simulatedReal.UseVectorFields, ...
    'FigureFieldVariant', cfg.branch.simulatedReal.FigureFieldVariant, ...
    'FigureWindowFactor', cfg.branch.simulatedReal.FigureWindowFactor, ...
    'FigureGridStyle', cfg.branch.simulatedReal.FigureGridStyle, ...
    'RealSpaceZoomFactor', cfg.branch.simulatedReal.RealSpaceZoomFactor, ...
    'FigureNames', cfg.branch.simulatedReal.FigureNames);

%% Render the field and Fourier figures
runConfiguredBranch(cfg, opts, ...
    'DataPath', fullfile(opts.DataPath, cfg.branch.fieldAndFourier.DataSubdir), ...
    'UseVectorFields', cfg.branch.fieldAndFourier.UseVectorFields, ...
    'FigureFieldVariant', cfg.branch.fieldAndFourier.FigureFieldVariant, ...
    'FigureWindowFactor', cfg.branch.fieldAndFourier.FigureWindowFactor, ...
    'FigureGridStyle', cfg.branch.fieldAndFourier.FigureGridStyle, ...
    'RealSpaceZoomFactor', cfg.branch.fieldAndFourier.RealSpaceZoomFactor, ...
    'FourierZoomFactor', cfg.branch.fieldAndFourier.FourierZoomFactor, ...
    'FourierUseLog', cfg.branch.fieldAndFourier.FourierUseLog, ...
    'FourierVectors', cfg.branch.fieldAndFourier.FourierVectors, ...
    'FourierVectorSpacingBase', cfg.branch.fieldAndFourier.FourierVectorSpacingBase, ...
    'FigureNames', cfg.branch.fieldAndFourier.FigureNames);

%% Render the reconstruction figures
runConfiguredBranch(cfg, opts, ...
    'DataPath', fullfile(opts.DataPath, cfg.branch.reconstruction.DataSubdir), ...
    'UseVectorFields', opts.ReconstructionVectors, ...
    'FigureNames', cfg.branch.reconstruction.FigureNames);

%% Return a short run summary
out = struct();
out.savePath = string(opts.SavePath);
out.dataPath = string(opts.DataPath);
out.figureCount = numel(cfg.figureSpec);
disp(out.savePath);
end

function runConfiguredBranch(cfg, opts, varargin)
%RUNCONFIGUREDBRANCH Execute one configured branch of the output set.
pinet_build_outputs( ...
    'FigureSpec', cfg.figureSpec, ...
    'SavePath', opts.SavePath, ...
    'RealVectorSpacingBase', opts.RealVectorSpacingBase, ...
    varargin{:});
end

function ensureDir(folderPath)
if ~exist(folderPath, 'dir')
    mkdir(folderPath);
end
end
