function cfg = pinet_config(rootDir)
%PINET_CONFIG Final self-contained configuration for the PINET export.

%% Resolve the package root
if nargin < 1 || isempty(rootDir)
    rootDir = fileparts(mfilename('fullpath'));
end

%% Package defaults
cfg = struct();
cfg.rootDir = string(rootDir);

cfg.defaults = struct( ...
    'SavePath', fullfile(rootDir, 'results_pinet'), ...
    'DataPath', fullfile(rootDir, 'data_pinet'), ...
    'RealVectorSpacingBase', 350, ...
    'ReconstructionVectors', true);

%% Figure groups
cfg.simulatedReal = { ...
    'Scattered electric field of an illuminated wire 1000' ...
};

cfg.fieldAndFourier = { ...
    'Fourier picture of scattered field'
    'Fourier picture of the scattered field after HPF of w over c'
    'Fourier picture of the scattered field after HPF of w over v'
    'Scattered electric field after HPF of w over c'
    'Scattered electric field after HPF of w over v' ...
};

cfg.reconstructionSet = { ...
    'Blurred reconstructed E with grid size of 30'
    'Median filtered reconstructed E with grid size of 200'
    'Perona-Malik diffused reconstructed E with grid size of 80'
    'Perona-Malik diffused reconstructed E with grid size of 110'
    'Perona-Malik diffused reconstructed E with grid size of 200'
    'Perona-Malik diffused reconstructed E with grid size of 500' ...
};

%% Exact exported figure specification
cfg.figureSpec = [ ...
    makeSpec('Scattered electric field of an illuminated wire 1000', 1000, "simulated_real", 1212, 515)
    makeSpec('Fourier picture of scattered field', 1000, "fourier_real", 1522, 660)
    makeSpec('Fourier picture of the scattered field after HPF of w over c', 1000, "hpf_c_fourier", 1522, 660)
    makeSpec('Fourier picture of the scattered field after HPF of w over v', 1000, "hpf_v_fourier", 1522, 660)
    makeSpec('Scattered electric field after HPF of w over c', 1000, "hpf_c_real", 1522, 660)
    makeSpec('Scattered electric field after HPF of w over v', 1000, "hpf_v_real", 1212, 515)
    makeSpec('Blurred reconstructed E with grid size of 30', 30, "blurred_rec", 1215, 517)
    makeSpec('Median filtered reconstructed E with grid size of 200', 200, "median_rec", 1212, 515)
    makeSpec('Perona-Malik diffused reconstructed E with grid size of 80', 80, "pm_rec", 1215, 517)
    makeSpec('Perona-Malik diffused reconstructed E with grid size of 110', 110, "pm_rec", 1215, 517)
    makeSpec('Perona-Malik diffused reconstructed E with grid size of 200', 200, "pm_rec", 1212, 515)
    makeSpec('Perona-Malik diffused reconstructed E with grid size of 500', 500, "pm_rec", 1215, 517) ...
];

%% Branch-level settings for the three output families
cfg.branch.simulatedReal = struct( ...
    'DataSubdir', 'simulated_real_static', ...
    'UseVectorFields', true, ...
    'FigureFieldVariant', 'static', ...
    'FigureWindowFactor', 5, ...
    'FigureGridStyle', 'legacy', ...
    'RealSpaceZoomFactor', 25, ...
    'FigureNames', {cfg.simulatedReal});

cfg.branch.fieldAndFourier = struct( ...
    'DataSubdir', 'field_fourier_phase', ...
    'UseVectorFields', true, ...
    'FigureFieldVariant', 'phase', ...
    'FigureWindowFactor', 5, ...
    'FigureGridStyle', 'legacy', ...
    'RealSpaceZoomFactor', 25, ...
    'FourierZoomFactor', 9, ...
    'FourierUseLog', false, ...
    'FourierVectors', true, ...
    'FourierVectorSpacingBase', 18, ...
    'FigureNames', {cfg.fieldAndFourier});

cfg.branch.reconstruction = struct( ...
    'DataSubdir', 'reconstruction_clean', ...
    'FigureNames', {cfg.reconstructionSet});
end

function item = makeSpec(name, gridSize, kind, width, height)
%MAKESPEC Create one figure specification entry.
item = struct( ...
    'Name', name, ...
    'GridSize', gridSize, ...
    'Kind', kind, ...
    'Width', width, ...
    'Height', height);
end
