function out = pinet_paper_reference_demo(varargin)
%PINET_PAPER_REFERENCE_DEMO Recreate the final PINET figure set.

rootDir = fileparts(mfilename('fullpath'));
cfg = pinet_final_config(rootDir);

p = inputParser;
addParameter(p, 'SavePath', fullfile(rootDir, 'results_paper_reference_demo'), @(x) ischar(x) || isstring(x));
addParameter(p, 'DataPath', fullfile(rootDir, 'data_paper_reference_demo'), @(x) ischar(x) || isstring(x));
addParameter(p, 'RealVectorSpacingBase', cfg.defaults.RealVectorSpacingBase, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'ReconstructionVectors', cfg.defaults.ReconstructionVectors, @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

ensureDir(opts.SavePath);
ensureDir(opts.DataPath);

runConfiguredBranch(cfg, cfg.branch.simulatedReal, opts, ...
    'DataPath', fullfile(opts.DataPath, cfg.branch.simulatedReal.DataSubdir), ...
    'UseVectorFields', cfg.branch.simulatedReal.UseVectorFields, ...
    'FigureFieldVariant', cfg.branch.simulatedReal.FigureFieldVariant, ...
    'FigureWindowFactor', cfg.branch.simulatedReal.FigureWindowFactor, ...
    'FigureGridStyle', cfg.branch.simulatedReal.FigureGridStyle, ...
    'RealSpaceZoomFactor', cfg.branch.simulatedReal.RealSpaceZoomFactor, ...
    'FigureNames', cfg.branch.simulatedReal.FigureNames);

runConfiguredBranch(cfg, cfg.branch.fieldAndFourier, opts, ...
    'DataPath', fullfile(opts.DataPath, cfg.branch.fieldAndFourier.DataSubdir), ...
    'UseVectorFields', cfg.branch.fieldAndFourier.UseVectorFields, ...
    'FigureFieldVariant', cfg.branch.fieldAndFourier.FigureFieldVariant, ...
    'FigureWindowFactor', cfg.branch.fieldAndFourier.FigureWindowFactor, ...
    'FigureGridStyle', cfg.branch.fieldAndFourier.FigureGridStyle, ...
    'RealSpaceZoomFactor', cfg.branch.fieldAndFourier.RealSpaceZoomFactor, ...
    'FourierZoomFactor', cfg.branch.fieldAndFourier.FourierZoomFactor, ...
    'FourierUseLog', cfg.branch.fieldAndFourier.FourierUseLog, ...
    'FourierVectors', cfg.branch.fieldAndFourier.FourierVectors, ...
    'FourierVectorSpacingBase', cfg.branch.fieldAndFourier.FourierVectorSpacingBase, ...
    'FigureNames', cfg.branch.fieldAndFourier.FigureNames);

runConfiguredBranch(cfg, cfg.branch.reconstruction, opts, ...
    'DataPath', fullfile(opts.DataPath, cfg.branch.reconstruction.DataSubdir), ...
    'UseVectorFields', opts.ReconstructionVectors, ...
    'FigureNames', cfg.branch.reconstruction.FigureNames);

out = struct();
out.savePath = string(opts.SavePath);
out.dataPath = string(opts.DataPath);
out.figureCount = numel(cfg.figureSpec);
disp(out.savePath);
end

function runConfiguredBranch(cfg, ~, opts, varargin)
pinet_recreate_reference_set( ...
    'FigureSpec', cfg.figureSpec, ...
    'SavePath', opts.SavePath, ...
    'RealVectorSpacingBase', opts.RealVectorSpacingBase, ...
    varargin{:});
end

function ensureDir(folderPath)
if ~exist(folderPath, 'dir')
    mkdir(folderPath);
end
end
